#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove features
rm -rf 0 constant/extendedFeatureEdgeMesh

rm -f constant/triSurface/{problemFaces,*.obj,combustor.stl,*.vtk,*.eMesh}

cleanCase
