#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# write the decomposition method at runtime
setDecompMethod(){ \
    foamDictionary -entry "method" -set $1 system/decomposeParDict;
}

# moving stator stator position 
surfaceTransformPoints translate="(0.2 0 0)" constant/triSurface/stator.bak.stl constant/triSurface/stator.stl

runApplication blockMesh

runApplication surfaceFeatures

#- -------------
if [ -n "$1" ] && [ "$1" -gt 1 ]; then

    foamDictionary -entry "numberOfSubdomains" -set "$1" system/decomposeParDict;

    setDecompMethod scotch;
       
    runApplication decomposePar

    runParallel snappyHexMesh
else
    runApplication snappyHexMesh
fi

# end-of-file
#- -------------
